NCAS-CMS/cf-python

- scripts/cfa
HI, I was just getting a feel for the codebase & noticed the ``cfa`` script has a specific user/path Python shebang at the very top, before the standard generic user one.
I suspect this is left in from a Python 3 porting development stage, as I can't see a purpose it would serve generally, & there is no equivalent Python 2 line in the earlier version of the same script up on Bitbucket.
I thought it would be easier to put in a PR to suggest to remove it than to write up an Issue. Thanks.
> cfa: remove specific user shebang

- docs/source/tutorial.rst
Hi again. I am about to raise several PRs to suggest some minor self-contained changes.
I have tried to group them to minimise the number of PRs to open whilst keeping suggested changes within each related. I'm happy to amend or close any of them if they aren't suitable for whatever reason. In each case I will add a changelog entry commit once the PR is opened so I know the hyperlink with the ID number to reference.
One question: for suggestions to changes to the documentation, I imagine you would like a PR to include the changes built via Sphinx & the Makefile to tupdated HTML files under ``docs/``? I've tried to do that in these cases, but I am having a problem building the docs whereby the ``make html ./`` command is not picking up on relevant modules despite them being present in my …
> Docs (tutorial): correct PP header items table entries

- docs/source/class.rst
- docs/source/field_analysis.rst
- docs/source/performance.rst
- docs/source/tutorial.rst
- docs/source/visualisation.rst
(As per #17, I will add a commit to build changes into the HTML files, once I can work out why I am getting errors trying to build the documentation.)
Whilst reading through the documentation I noticed a few typos, so I thought I could run over most of the core documentation content via all the ``.rst`` files under ``docs/source/`` with a pipeline command extracting the plain text & sending it to the``aspell`` spelling checker. Here are corrections from doing that. There is also one formatting error I noticed by eye.
> Docs (all): fix spelling & formatting errors & typos

- docs/source/tutorial.rst
(As per #17, I will add a commit to build changes into the HTML files, once I can work out why I am getting errors trying to build the documentation.)
In the ['Inspection' section of the documentation tutorial](https://ncas-cms.github.io/cf-python/tutorial.html?highlight=lbproc#inspection) there is reference to the built-ins ``repr()`` & ``str()``, but in the subsequent code examples those built-ins are not called directly, rather called under the hood by calling, & by calling ``print()`` on, respectively, the field construct (or dataset, etc.).
To someone without relevant knowledge of Python to know that ``print()`` show the ``str()`` etc. I think it could be unclear as to how the code snippets & the functions referred to relate, so I suggest adding something similar to that proposed …
> Docs (tutorial): add context for referenced functions

- .github/workflows/run-test-suite.yml
- cf/test/run_tests.py
- setup.py
The external GH Action ``goanpeca/setup-miniconda`` has been updated with a new release to including the new option to use custom conda channels. I included it prematurely on the previous attempt at getting the test suite workflow to run (#48) such that it failed, but it should work now, so this is another test run.
I've changed the syntax for the ``on > push`` specification of ``master`` in case there was an issue with that, but the workflow still does not seem to be triggered from commit to ``master`` (my recent commit 36773aad1179f6732f134f053b7b5dad5e70ddab did nothing). My working theory (given lack of info online) is that trigger-by-push only works when the workflow is defined in the same branch, & here I am using a separate branch. Can check this once the workflow works & I merge …
> Add GitHub Action workflow to run test suite

- cf/functions.py
> Close /proc/meminfo at exit

- .github/workflows/run-test-suite.yml
- docs/source/installation.rst
- docs/source/tutorial.rst
Some documentation commits. Putting these in via PR because I want to do some work on the GH Actions workflow (specifically, get the environment set up so the ``test_PP_*`` tests can pass) & want to stick to having triggering with PRs only.
> Documentation: notes on verbosity & versioning

- Changelog.rst
- cf/cfdatetime.py
- cf/constants.py
- cf/field.py
- cf/functions.py
- cf/mixin/propertiesdata.py
- cf/read_write/netcdf/netcdfwrite.py
- cf/read_write/read.py
- cf/read_write/write.py
- cf/test/test_Maths.py
- cf/test/test_function.py
- cf/test/test_groups.py
- docs/source/function.rst
Final step towards & therefore closes #70, after work to convert all functions to get & set individual global constants to lower-case was completed in #93. This is equivalent to NCAS-CMS/cfdm#61 but is more complicated as there are many more global constant settings to include for `cf` (13 vs. 3 for `cfdm`).
Opening as a WIP because in implementing this, particularly the unit test, I noticed that `cf.atol` & `cf.rtol` are detached from the corresponding constants in `cf.CONSTANTS`, instead getting & setting the `cfdm` equivalent (see #85 where I will detail it further). I would like to fix this first before completing this PR as it causes the unit test to fail (for valid reason). Best wait until the underlying issue is addressed to merge with a passing unit test (without bodging it …
> New function cf.configuration with unit test

- cf/abstract/coordinate.py
- cf/cellmethod.py
- cf/coordinatereference.py
- cf/data/data.py
- cf/data/partitionmatrix.py
- cf/dimensioncoordinate.py
- cf/field.py
- cf/mixin/coordinate.py
- cf/mixin/properties.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_DimensionCoordinate.py
- cf/test/test_Field.py
- cf/test/test_read_write.py
*    implements __inplace keyword to set_data methods
*    implements a choice of default value for in place int he `@_inplace_enabled` decorator. An upshot of this is that the default has to specified in all cases. No bad thing.
*    Allows "data_like" inputs instead of `cf.Data` objects:
_A data_like object is any object that can be converted to a Data object, i.e. numpy array_like objects, Data objects, and cf objects that contain Data objects._
> set_data, inplace default, data_like

- cf/aggregate.py
- cf/test/test_aggregate.py
Close #116 with a new test to isolate the previous bug minimally, and also fill in all of the placeholders for error messages elsewhere in `cf.aggregate`.
> Fixes and error messages for cf.aggregate

- .github/workflows/run-test-suite.yml
- .github/workflows/test-source-dist.yml
- test_release
Closes #136 by adding a new workflow to run a pair of jobs, one for each of the latest OSs (Ubuntu & Mac OS), both with Python 3.7 as a representative version, where each job:
1. sets up the required cf-python environment by installing dependencies etc.;
2. creates the source dist from the state of the checked-out codebase;
3. (and ultimately) tests the source dist via `./test_release <vn>`.
I am putting this in via PR instead of pushing the commit because I want to check the new two jobs run and triggering is set only for PR, not for pushes (there is no need to test the sdist that often as the results shouldn't vary *too* much from the standard test suite results, if at all). I don't expect the jobs to succeed, however (as there are errors still under investigation which are likely to …
> Workflow to create and test source dist for all PRs

- Changelog.rst
- cf/aggregate.py
- cf/test/test_aggregate.py
Fix bug alluded to in #150 (though it is not the core of the issue raised there, so it does not resolve it), namely that the verbosity keyword is ineffectual:
> I also tried to debug this issue with argument verbose. However, no matter what value that I set to verbose, there was not any extra information shown.
This turned out to be because a decorator was not applied to a central method for logging output during aggregation, `print_info`. A one-line change to add the decorator fixes the problem.
To ensure it did fix it and for robustness I have added a unit tests for the verbosity on `cf.aggregate` specifically (though the verbosity decorators are themselves unit tested, `cf.aggregate` in particular warrants a specific test that the verbosity is managed correctly since it involves a mix …
> Re-establish configurable verbosity for cf.aggregate

- cf/data/data.py
- cf/test/test_Data.py
Fixes bug that caused `partition.config['units']` to be inconsistent with the units of the partition array when carrying out binary arithmetic during which the result units are different than the input units.
This is long standing, and only manifests when the partition is being cached to disk, and the result units are different than the input operand units.
> fixed stored partition config

- cf/functions.py
- cf/test/test_Data.py
- cf/test/test_aggregate.py
- cf/test/test_functions.py
Some amendments relating to `cf.environment` which don't modify its behaviour in any way, namely:
* remove a defunct keyword argument from the signature;
* refactor the code which had quite a bit of duplication and wasn't as readable as it could be;
* add a basic test.
> Refactor and test for cf.environment

- cf/aggregate.py
- cf/cellmethod.py
- cf/coordinatereference.py
- cf/data/data.py
- cf/field.py
- cf/fieldlist.py
- cf/functions.py
- cf/mixin/properties.py
Closes #132.
Now the linting pre-commit checks are passing after #194, I want to check if Python 3.9 passes the CI to confirm the resolution of #132. It passes for me locally as far as I can tell around the seg faults which are still occurring and under investigation (see #180), though the seg faults may also appear on the Actions jobs since we have seen them emerge there before.
Since the Actions jobs for the workflow to run the test suite are only set to be triggered by PR, I am putting in a trivial PR to trigger and inspect the jobs. These trivial commits fix  all of the syntax errors raised by doctest on the codebase (I have set up a CLI option `-d` so we can check these via `py run_tests.py -d` towards #4, though until they are all passing I won't add them to the test suite).
> Fix docstring example syntax errors and test Python 3.9

- Changelog.rst
- cf/read_write/read.py
- cf/test/test_read_write.py
See #197 and #NCAS-CMS/cfdm#128 for details.
Note in response to the CI failing on coverage I've realised that even for this short-term fix I should add some more tests to cover metadata-only CDL, so I need to create and commit those before this can be merged.
> Short-term fix for errors in reading of metadata-only CDL

- Changelog.rst
- cf/aggregate.py
- cf/test/test_aggregate.py
> Fix for cf.aggregate failures when field units are non-valid

- Changelog.rst
- cf/functions.py
- cf/read_write/read.py
- cf/test/test_read_write.py
Close #171 using the (same) new keyword as suggested in the opening comment of that tagged Issue and in doing so, also improve the error handling for invalid CDL inputs generally.
Note that the API update with the new `cdl_string` keyword argument is (admittedly) a little clunky, given the core (and only non-keyword) argument is named `files` and always accepts file locations other than with this new keyword set to `True` where it then changes to instead accept a string of CDL input (though strictly OPenDAP URLs are also possible to already break the general pattern too, so maybe it is not so bad). However, the only alternative in practice would be to create a whole new function, `cf.read_from_string` or similar, for the case of reading from a string, only possible with CDL anyway.
So, …
> New cf.read kwarg enabling CDL string input

- cf/field.py
- cf/regrid/regridoperator.py
- cf/regrid/utils.py
resolve #222
The special methods `__del__` of `ESMF.Field` and `ESMF.Grid` objects feature calls to their respective `destroy` methods that release the memory allocated by ESMF in Fortran. When these objects go out of scope, the Python garbage collection ought to call these `__del__` methods, yet their allocated memory does not seem to be released properly, as repeatedly regridding fields results in running out of memory after a while.
After a discussion with @davidhassell, we suspect that the `ESMF.Manager` may be responsible for not making the memory release possible as long as it stays in scope. However, in `cf` the Manager is initialised but not bound to a variable name (see e.g. https://github.com/ThibHlln/cf-python/blob/d9cde28d9abd9cfeb6575c737560956f40620942/cf/field.py#L15619), …
> Fix regrid memory leak

- Changelog.rst
- cf/constants.py
- cf/coordinatereference.py
- cf/test/test_CoordinateReference.py
> Fix for cf.aggregate failure when a datum or coordinate conversion parameter has an array value

- cf/mixin/fielddomain.py
- cf/test/test_Field.py
To close #236 and (if we want to keep it as a method, see suggestion below), in the process improve the testing and documentation of `Field.get_coordinate_reference`.
I have made the basic update to apply the construct access API change that was missed for v3.10.0 via cfdm v1.8.9.0, in 32a8787, but this PR remains a draft because I also want to flash out the corresponding API documentation but:
* I am [also unsure](https://github.com/NCAS-CMS/cf-python/issues/236#issuecomment-881358028) of the intended role of the `construct` keyword.
* It is not entirely clear to me from the code (given the lack of summary line in the docstring/docs) the intention of the method `Field.get_coordinate_reference`, in particular how it differs to `cf.Field.coordinate_reference` (from `cf`) and …
> Concerning `Field.get_coordinate_reference`

- .github/workflows/dask-migration-testing.yml
- cf/test/test_Data.py
I am about to put up some more interesting PRs to make headway with 'Daskifying' the data-related methods in turn for #182, but before I start doing that in earnest I want to ensure we can track the migration progress in terms of the tests that pass, notably for (self-)review to:
* indicate progress for a given PR by highlighting extra tests that pass due to a given change; and
* ensure tests that do pass due to progress previously made aren't broken by any proposed changes in a new PR.
So in this PR I have:
* added skips to tests in `test_Data`  that can be switched on or off by a new flag `TEST_DASKIFIED_ONLY`;
* added a new workflow specifically specifically for the LAMA-to-dask migration work to trigger Github Actions to run jobs that run the `test_Data` module and not the whole test …
> `test_Data` workflow with skips to monitor Dask migration

- cf/data/data.py
One final PR for some setup and helper code related to the LAMA to Dask migration (#182) before I start pushing up the actual method migrations in turn!
This one adds a temporary custom decorator that will be applied to directly mark methods that we consider to have been migrated fully in the code, so we don't have to cross-reference with the very long checklist in the issue (though I will make sure to update the list too upon each corresponding merged PR). As well as acting as a marker, the decorator provides a log message reported each time the method is run (which can be adapted to provide more info, as useful) and allows the log level to be tuned for those methods only by simply changing the decorator argument value.
I have marked all methods considered 'daskified' after …
> Temporary decorator to mark & log 'daskified' methods

- cf/data/data.py
- cf/data/mixin/__init__.py
- cf/data/mixin/deprecations.py
Towards reducing the size of the `data.data` module (currently ~15,000 lines), move out the deprecated and newly-deprecated (for the dask migration) attributes and methods of the `Data` class into a new module by creating a dedicated mixin class `DataClassDeprecationsMixin` to house them. (Also, in b18f653, address one minor warning that was being raised by the `test_Data` run.)
> Move deprecated data attrs & methods out into mixin

- cf/test/test_Data.py
Towards #182, remove the loop over, and context management of, chunk sizes in `test_Data`.
Chunk size is a LAMA-related aspect and we can assume (at least until the Data module migration is more complete and we can think about how rigorous this test module needs to be and how to improve it) that the data array memory management is tested thoroughly by Dask so that we don't need to effectively test over a range of sizes of partitions of the sub-arrays.
As a result, three extra tests pass (after being un-skipped) relative to those passing before, since the non-existent attribute of `chunk_sizes` being called in the test turned out to be the only migration issue left in those small number of cases.
> Remove loops over chunksize in `test_Data`

- Changelog.rst
- cf/field.py
- cf/formula_terms.py
- cf/regrid/utils.py
- cf/test/test_regrid.py
resolves #250 
Hi David, Hi Sadie,
With the simple change contained in this PR, the code below would work, which is not currently the case (i.e. a regridding towards a single grid cell domain).
```python
import cf
import numpy
fld1 = cf.Field()
fld1.set_construct(
cf.DimensionCoordinate(
properties={'standard_name': 'longitude',
'units': 'degrees_east',
'axis': 'X'},
data=cf.Data([5, 15, 25]),
bounds=cf.Bounds(data=cf.Data([[0, 10], [10, 20], [20, 30]]))
),
axes=fld1.set_construct(cf.DomainAxis(size=3))
)
fld1.set_construct(
cf.DimensionCoordinate(
properties={'standard_name': 'latitude',
'units': 'degrees_north',
'axis': 'Y'},
data=cf.Data([55, 65]),
bounds=cf.Bounds(data=cf.Data([[50, 60], [60, 70]]))
),
axes=fld1.set_construct(cf.DomainAxis(size=2))
)
fld2 = cf.Field() …
```
> Restrict size 1 limitation to source field in regridding

- cf/data/data.py
- cf/data/utils.py
- cf/query.py
- cf/test/test_Data.py
- cf/test/test_Query.py
Includes in `cf.Query` a bug-fix and new utility method `set_condition_units`.
> dask: `Data.where`

- cf/data/data.py
- cf/field.py
- cf/mixin/propertiesdata.py
- cf/test/test_Data.py
> Allo element-wise comparisons with `None`

- Changelog.rst
- cf/aggregate.py
- cf/test/test_aggregate.py
> Fix `cf.aggregate` failures when using the 'dimension' keyword

- Changelog.rst
- cf/test/test_TimeDuration.py
- cf/timeduration.py
Close #287 and add a test to capture it that bug, as well as a similar bug with a different traceback emering if the inverse is tried i..e the data subtracted from the timeduration (which I guess makes sense and should work, though isn't a very natural operation), namely (this report results from adding the new test lines to the `master` branch:
```python
test_TimeDuration (__main__.TimeDurationTest) ... ok
test_TimeDuration_arithmetic (__main__.TimeDurationTest) ... ERROR
test_TimeDuration_bounds (__main__.TimeDurationTest) ... ok
test_TimeDuration_interval (__main__.TimeDurationTest) ... ok
test_TimeDuration_iso (__main__.TimeDurationTest) ... ok
test_Timeduration__days_in_month (__main__.TimeDurationTest) ... ok
====================================================================== …
```
> Fix subtraction of `TimeDuration` of, and from, `Data`

- Changelog.rst
- cf/field.py
- cf/test/test_Field.py
> Fix bug in `cf.Field.derivative` and `cf.relative_vorticity` when   wrapping with periodic coordinates

- .github/workflows/run-test-suite.yml
- .github/workflows/test-source-dist.yml
A netCDF file for testing on, `test_file.nc` is written out and used by the `run_test.py` script that runs the full test suite, and locally this works fine, but for the Actions jobs it is not being recognised, at least within the `test_Field` module:
```bash
Running tests from /home/runner/work/cf-python/cf-python/main/cf/test
class FieldTest(unittest.TestCase):
File "/home/runner/work/cf-python/cf-python/main/cf/test/test_Field.py", line 80, in FieldTest
f = cf.read(filename)[0]
File "/home/runner/work/cf-python/cf-python/cfdm/cfdm/decorators.py", line 171, in verbose_override_wrapper
return method_with_verbose_kwarg(*args, **kwargs)
File "/home/runner/work/cf-python/cf-python/main/cf/read_write/read.py", line 699, in read
open(file_glob, "rb")
FileNotFoundError: [Errno 2] No such file …
```
> CI: create `test_file.nc` before step to run test suite

- cf/timeduration.py
After #288 I noted (to myself) it would be helpful to consolidate the `timeduration` module as there was considerable duplication of logic, and best do that for the next release and before I focus in on the Dask migration work fully, hence a quick PR now.
The corresponding changes are trivial enough that peer review seems unnecessary and there are no functional changes so no changelog update required (etc.).
> Reduce duplication in `TimeDuration` via internal methods

- Changelog.rst
- README.md
- cf/__init__.py
- cf/docstring/docstring.py
- cf/field.py
- cf/maths.py
- cf/test/test_Data.py
- cf/test/test_Field.py
- cf/test/test_Maths.py
- docs/source/class/cf.Field.rst
- docs/source/field_analysis.rst
- docs/source/function.rst
- docs/source/introduction.rst
> New differential operators: Laplacian, grad, div, and curl

- cf/data/data.py
- cf/test/test_Data.py
Convert the `Data.func` method towards #182, in doing so daskifying several other element-wise operation methods that use it to perform the underlying operation, as follows (though note the below context since in short most of these can and will be then converted to use Dask built-ins rather than calling `func`):
- the trigonometric and hyperbolic methods and their inverses (12 in total: `sin`, `arcsin`, `sinh`, `arcsin` etc.);
- `ceil`;
- `exp`;
- `floor`;
- `rint`;
- `round`;
- `trunc`;
and daskifying `log` except in the case of setting a base that isn't `e`, `2` or `10` which requires which requires `__itruediv__` to be daskified to work.
As well as daskifying `func` this PR effectively daskifies the other methods listed above in doing so because they use `func` to operate in the code …
> `Data.func` and friends: migrate to Dask

- cf/data/data.py
- cf/test/test_Data.py
Partially address #302, to tick all sub-issue boxes except the topmost\* and in doing so close #303, since `Data.log` is now fully migrated (and marked as such) because the `/=` operator it uses with a non-`e`/`10`/`2` based is applied in 'Dask space' rather than `cf` space.
\* the topmost item,  '_the eight trigonometric and hyperbolic methods and their inverses which don't have restricted domains_', will be tackled as a separate PR to make it easier for the reviewer to check that the correct eight methods have been converted and in a consistent way, with commenting to explain why the other four such methods have been left as `func` calls. And since the code changes required on all of the methods listed in #302 are largely the same, such that any review feedback can be done as one on …
> LAMA to Dask: `func` -> built-in conversion for non-trig. methods

- cf/data/data.py
Close #302 by addressing the final item, namely to convert 'the eight trigonometric and hyperbolic methods and their inverses which don't have restricted domains' and also, for completeness, adding comments to the other four such methods to indicate why they haven't been converted in this way.
> LAMA to Dask: func -> built-in conversion for trig. methods

- .github/workflows/dask-migration-testing.yml
For context, see https://github.com/NCAS-CMS/cf-python/pull/313#issuecomment-1033476035 and related comments in that thread. Also adding Python 3.10 whilst I am amending the workflow matrix, as that is now available and it is a good idea to start testing with it.
Trivial change but opening as a PR instead of committing directly to the branch in order to check the remaining jobs pass. (`lama` was changed to Llama somehow when writing the commit message here and it can stay for amusement value / because I can't be bothered to rebase to re-word).
> CI: drop Python 3.7 & add 3.10 for `lama-to-dask` workflow

- cf/test/test_Data.py
Quick PR to suppress some specific expected warning messages which are presently clogging up the `test_Data` output, and address a lone deprecation warning at the same time.
Not strictly a Dask migration PR (just tidying the relevant test), and contains nothing controversial, so no review required.
> Manage warnings in `test_Data`

- cf/data/data.py
- cf/test/test_Data.py
Convert the `mask` managed attribute towards #182.
> `Data.mask`: migrate to Dask

- cf/umread_lib/c-lib/Makefile
This works around what seems to be some kind of compiler / linker bug.
In the conda environment we are using, containing:
```
$ gcc --version
gcc (GCC) 11.2.0
[...]
$ ld --version
GNU ld version 2.27-44.base.el7
[...]
```
I find that I can't create a shared library if `-g` has been used in the compilation:
```
$ cat foo.c
void foo() {}
$ gcc -c -g foo.c
$ ld -shared -o foo.so foo.o
ld: foo.o: unable to initialize decompress status for section .debug_info
ld: foo.o: unable to initialize decompress status for section .debug_info
foo.o: file not recognized: File format not recognized
```
without the `-g`, everything looks normal
```
$ rm foo.o
$ gcc -c foo.c
$ ld -shared -o foo.so foo.o
$ nm foo.so
0000000000201000 D __bss_start
0000000000200f50 d _DYNAMIC
0000000000201000 D _edata …
```
> remove "-g" (include debug flags) compiler option

- Changelog.rst
- cf/__init__.py
- docs/source/installation.rst
- requirements.txt
When running test modules e.g. `test_Data` under `pytest` (as can be done via `$ pytest <test module>` even though we don't strictly use `pytest` but `unittest`), I get multiple deprecation warnings on several uses of `distutils.version.LooseVersion`, all in `cf/__init__.py`:
```console
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
g["version"][version] = LooseVersion(version)
```
I have updated these here to `packaging.version.Version`; it actually wasn't at all clear in any of the relevant documentation as to which class from that module would be the appropriate replacement, but from doing a full-GitHub search on relevant keywords I found the following comments ([this](https://github.com/pydata/xarray/pull/6096#issue-1086346755) and …
> Update deprecated `distutils.version` to `packaging.version`

- cf/data/data.py
- cf/test/test_Data.py
Fix a bug in `Data.flip`, exposed with the following example, which was lifted from the start of the `test_Data_BINARY_AND_UNARY_OPERATORS` test, which is where the bug was noticed:
```py
a = np.arange(3 * 4 * 5).reshape(3, 4, 5) + 1.0
a0 = a[(slice(None, None, -1),) * a.ndim]
d = cf.Data(a0)
d.flip()
```
which, on the present `lama-to-dask` branch, runs into:
```pycon
~/cf-python/cf/data/data.py in <listcomp>(.0)
10958 
10959         index = [
> 10960             slice(None, None, -1) if i in axes else slice(None) for i in iaxes
10961         ]
10962 
TypeError: argument of type 'NoneType' is not iterable
```
though it is not just a case of converting the `axes` into a sequence if an integer value was provided (both are permitted as values for that keyword), since there is a further …
> Fix bug in previously-daskified `Data.flip`

- cf/data/dask_utils.py
- cf/test/test_Data.py
Fix `Data.equals` for arbitrary chunk distributions.
> dask: fix `Data.equals` for arbitrary chunk distributions

- cf/data/dask_utils.py
- cf/data/data.py
- cf/test/test_Data.py
`Data.__contains__` was already daskified, but the unit test was being skipped. This PR re-instates the unit test, and takes an opportunity to improve the code (notable adding some short circuits).
> dask: `Data.__contains__`

- cf/aggregate.py
- cf/test/test_aggregate.py
Fixes #341
Fixes the issue, and a bit of code tidy thrown in that resulted from a red herring that I pursued before properly understanding the requirements.
> Fixes setting both relaxed_identities=True and ncvar_identities=True in `cf.aggregate`

- cf/data/data.py
- cf/functions.py
- cf/test/test_Data.py
The `masked_as_zero` keyword has been deprecated because the person who requested it originally a) hasn't ever used it, b) says he doesn't need it and c) I think that its functionality was a bit confused. So, all in all I hope we can make this API change without any worries.
> dask: `Dask cumsum`

- cf/test/test_Data.py
Just activates the test - the method was daskified long ago.
> dask: `Data.roll`

- cf/data/data.py
- cf/docstring/docstring.py
- cf/test/test_Data.py
Just docs and tests. Code changes were already there.
> dask: `Data.chunks` and `Data.rechunk`

- cf/data/data.py
- cf/functions.py
- cf/test/test_Data.py
No dask implications here, just tidying up something that never really got finished from way back.
> dask: `Data.HDF_chunks`

- cf/data/data.py
- cf/test/test_Data.py
units/calendar compatibility with parent `cfdm.Data`
> dask: `Data` units and calendar methods inherited from cfdm 

- cf/data/abstract/compressedsubarray.py
- cf/data/abstract/filearray.py
- cf/data/cachedarray.py
- cf/data/collapse_functions.py
- cf/data/creation.py
- cf/data/data.py
- cf/data/filledarray.py
- cf/data/functions.py
- cf/data/mixin/deprecations.py
- cf/data/netcdfarray.py
- cf/data/partition.py
- cf/data/partitionmatrix.py
- cf/data/umarray.py
- cf/data/utils.py
As for NCAS-CMS#182 over on cfdm, but note that this is **only across the data module**, i.e:
```console
$ pwd
<path to cf repo>/cf-python/cf/data
$ find . -type f | xargs sed -i 's/Examples:/Examples/g'
```
in line with our approach to managing development of mostly `data` modules on `lama-to-dask` and all other modules on `master`. I am about to open a corresponding PR on `master` to cover all non-`data` modules.
@davidhassell I have opened this PR so the batch update gets done at the first available point, but please prioritise merging of your currently-open PRs before this - it is trivial to manage code updates and to resolve merge conflicts here, much less so (probably) on your PRs.
> `data` batch docstring re-formatting: 'Examples:' -> 'Examples'

- cf/data/abstract/compressedsubarray.py
- cf/data/abstract/filearray.py
- cf/data/cachedarray.py
- cf/data/collapse_functions.py
- cf/data/creation.py
- cf/data/data.py
- cf/data/filledarray.py
- cf/data/functions.py
- cf/data/mixin/deprecations.py
- cf/data/netcdfarray.py
- cf/data/partition.py
- cf/data/partitionmatrix.py
- cf/data/umarray.py
- cf/data/utils.py
Reverts NCAS-CMS/cf-python#362, by agreement with @davidhassell, since the resultant merge conflicts in parallel PRs were more tricky than anticipated. We will re-apply these changes in a new PR once most or all of the recent PRs have been merged.
> Revert "docstring re-formatting: 'Examples:' -> 'Examples'"

- cf/data/data.py
- cf/data/mixin/deprecations.py
- cf/functions.py
- cf/test/test_functions.py
Hi Sadie, I think deprecating `__hash__` is the good thing to do because it was never used in the library code; it's exact functionality is still in `cf.hash_array`; and it was never a good hash of a `Data` object, anyway, as it it didn't include units, cyclic axes, etc.
> dask: `Data.__hash__`

- cf/data/data.py
`_set_subspace` is no longer needed, as it's functionality has been replicated in `__setitem__`, and the slicing of chunks is now out of our control (i.e. dask deals with it)
> dask: `Data._set_subspace`

- cf/data/data.py
`_parse_indices` inherited from cfdm has been replaced with `cf.parse_indices` (because the functionality is also used elsewhere), and so the former should not be used.
> dask: `Data._parse indices`

- cf/data/data.py
- cf/mixin/propertiesdata.py
- cf/query.py
Just deleting these methods, as they merely duplicate code in `cf.Query` (https://github.com/NCAS-CMS/cf-python/blob/v3.12.0/cf/query.py#L667-L710). That code is already as efficient as it can be for dask arrays.
> dask: `Data` query interface

- cf/data/data.py
- cf/data/mixin/deprecations.py
- cf/test/test_Data.py
`__round__` is not implemented by numpy nor dask - I reckon it's OK to also not implement it here.
> dask: `Data.__round__`

- cf/functions.py
Quick one to fix a formatting issue (spotted in https://github.com/NCAS-CMS/cf-python/pull/395#pullrequestreview-966168080) due to a (valid) change that went in as part of #384 but which has been partially reverted, likely due to a merge conflict resolution mistake somewhere along the line.
Before this PR for e.g. `d.ismasked()` on some `cf.Data`:
```python
DeprecationError: Data attribute 'ismasked' has been deprecated at version TODODASK and will be removed at version  and will be removed at version 5.0.0. Use the 'is_masked' attribute instead
```
And after this PR, the obvious fix is made:
```python
DeprecationError: Data attribute 'ismasked' has been deprecated at version TODODASK and will be removed at version 5.0.0. Use the 'is_masked' attribute instead
```
No review requested as …
> Fix formatting of message for deprecated attributes

- cf/data/dask_utils.py
- cf/data/data.py
- cf/test/test_Data.py
Code reorganisation for consistency. Also new unit test.
> dask: `Data.Units`

- cf/test/test_Data.py
Just some unit tests for inherited methods.
> dask: `Data.get_compression_axes` and friends

- cf/data/data.py
- cf/data/mixin/deprecations.py
- cf/test/test_Data.py
Following on from https://github.com/NCAS-CMS/cf-python/issues/365, I think that this method is just too "dangerous", now, and it would be better to manage this from the `Field`/`Domain`, with content injected by `cf.read`/`cf.aggregate`. All of which would be the topic of a later PR.
> dask: `Dask.get_filenames`

- Changelog.rst
- cf/test/test_decorators.py
- docs/source/installation.rst
- requirements.txt
Fixes #419
See https://github.com/NCAS-CMS/cfdm/pull/197 for details.
> Fix test_decorators issue by setting correct assertLogs levels

- cf/data/data.py
- cf/data/mixin/deprecations.py
Migrating the `Data.concatenate_data` method towards #182, by deprecating it.
I don't think this approach will be controversial (so-as to have required pre-PR discussion) since it seems to be essentially the same method as `concatenate`, just compare the inputs and outputs on the docstrings to see this, with no real difference except for the behaviour of:
> In the case that the list contains only one element, that element is simply returned.
and it is not used anywhere throughout the codebase, unlike `concatenate` which is used quite widely (note this was a post-PR grep, but regardless the only usage is to define it):
```console
$ pwd
/home/sadie/cf-python/cf
$ git grep "concatenate_data"
data/mixin/deprecations.py:    def concatenate_data(cls, data_list, axis): …
```
> LAMA to Dask: (deprecate) `Data.concatenate_data`

- cf/data/dask_utils.py
- cf/data/data.py
- cf/data/utils.py
- cf/formula_terms.py
- cf/test/test_Data.py
Tidies the `lama-to-dask` branch in the following ways:
* addresses https://github.com/NCAS-CMS/cf-python/pull/425#discussion_r930734685;
* addresses https://github.com/NCAS-CMS/cf-python/pull/425#discussion_r931689805;
* makes formatting tweaks from running `pre-commit run --all-files` for a pass, to apply all required (not much, in this case, but some) auto-formatting across the codebase;
* adds appropriate docstrings to all of the `test_Data` methods (`docformatter` now checks these); 
* un-skips three `test_Data` tests which pass due to other migration progress, but hadn't yet been un-skipped (three skips remain across the module, which we will consider separately to this PR). 
See the separate commits which each focus on one of the five above (should be obvious which).
@davidhassell …
> LAMA to Dask migration: branch tidy

- cf/cfdatetime.py
- cf/data/creation.py
- cf/data/data.py
- cf/data/utils.py
- cf/field.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_Data.py
- cf/test/test_Field.py
Hi Sadie, bit rambling, but fixes a bug that didn't allow `Data` objects to be instantiated from datetime objects, and also one that prevented constructs from being combined with Query objects, in some circumstances (the latter uncovered the former).
> dask: datetime `Data` init, and combination with `Query` objects

- cf/data/data.py
- cf/test/test_Data.py
Allow `Data.Units` assignment when the data units have no been set.
> dask: `Data.Units` @Units.setter

- cf/test/test_Field.py
Removes non-needed `varray` call in test.
> dask: `FieldTest.test_Field_transpose`

- cf/data/data.py
- cf/domain.py
- cf/test/test_Data.py
This fix allows `test_Field_cell_area` and `test_Field_weights` to pass.
> dask: `Data.outerproduct` _axes/_cyclic fix

- cf/data/data.py
- cf/test/test_TimeDuration.py
Sometime dask's `compute` returns a numpy int/float type rather than a scalar array, which doesn't work well with downstream methods (like `Data.__array__`), so `Data.array` make sure we trap those cases and cast it as a proper scalar array.
Also some housekeeping in `test_TimeDuration.py` (no substantive changes).
> dask: `Data.array` return type (and test housekeeping)

- cf/read_write/netcdf/netcdfread.py
- cf/test/test_read_write.py
Not entirely sure  know why the `g["cfa"]` items worked before, but replacing them with `g.get("cfa")` seems safe.
> Reinstate read/write tests, account for CFA files

- cf/data/data.py
- cf/data/utils.py
- cf/field.py
- cf/test/test_Data.py
- cf/test/test_Field.py
A bit of a tidy, and a change to `Data.where` to allow leading size one dimensions. Deleted the `_broadcast` function as it is not used.
> dask: `Field.where`

- cf/data/data.py
- cf/field.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
Propagating changes from `Data.halo` (#331).
> dask: `Field.halo`

- cf/field.py
- cf/test/test_Field.py
API changes:
* `masked_as_zero` parameter deprecated (see #343 for details)
* `coordinate` parameter deprecated. This is because it was always flaky, and I didn't want to make the effort to daskify dodgy code that will be going anyway. It is flaky because it allowed non-CF compliant dimension coordinates to be created automatically. Specifically, the moving of the coordinate coordinate values could result in non strictly monotonic values, because the bounds do not have to follow this restriction.
> dask: `Field.cumsum`

- cf/data/data.py
- cf/test/test_Data.py
Migrates the `Data.stats` method towards https://github.com/NCAS-CMS/cf-python/issues/182.
Since `stats` is a compound method, in that it is in essence just reporting the outputs from various other `cf` stats/collapsing methods, each of which have already been 'daskified' hence utilise dask under-the-hood, the simplest way to migrate with full performance (bar working out and making use of any sub-calculation operations which might be shared between any of the statistics or something like that which would surely be over the top for our purposes?) is (I believe) to run each statistic calculation in parallel, which in Dask world for this context is done with `delayed` functions and a final `compute`.
This PR implements this. As indicated by the resultant Dask task graph shown below, all …
> LAMA to Dask migration: `Data.stats`

- cf/data/data.py
- cf/data/mixin/arraymixin.py
A few changes to help `test_docstring.py` pass. In particular, the `@daskified` decorators weren't playing nicely with the test, so I've removed them. They have been very useful, but I think they are no longer needed given how far along we are.
> dask: Changes to allow test_docstring.py to pass

- Changelog.rst
- cf/aggregate.py
- cf/field.py
- cf/test/test_aggregate.py
> Fix bug that raises an exception when using the `equal` or `exist` keyword of `cf.aggregate` 

- cf/test/test_pp.py
- cf/test/test_read_write.py
Fix up the PP read test from `test_read_write.py` and move it to its spiritual home in `test_pp.py`.
> Move test to `ppTest`

- cf/read_write/netcdf/netcdfread.py
Minor bug fix for the new element caching for `Data.__str__`.
> dask: Fix for cached str-type data elements

- cf/abstract/constructlist.py
- cf/constructs.py
- cf/coordinatereference.py
- cf/domain.py
- cf/field.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_FieldList.py
- cf/test/test_geometry.py
Deprecates `close` methods, and removes the corresponding tests.
> dask: Deprecate `close`

- cf/data/array/mixin/filearraymixin.py
Remove `FileArrayMixin._dask_lock`. The property was returning `True`, which created a lock on chunk reads in `data.creation.to_dask`, preventing concurrent reads from data on disk and effectively creating turning off parallelism by forcing sequential behaviour.
In the absence of a `_dask_lock`, the lock passed to `dask.array.from_array` is `False`, which allows concurrent reads.
> dask: Remove `FileArrayMixin._dask_lock`

- cf/read_write/netcdf/netcdfread.py
- cf/test/test_groups.py
Fix for incorrect reading of VLEN string variables from netCDF4 files. I don't know why this was failing, but new change reuses code from cfdm, rather than cutting and pasting, which has to be better! This allows `test_groups.py` to pass.
Need https://github.com/NCAS-CMS/cfdm/pull/235 to be merged first. _Edit: which has now happened_
> dask: Correctly read VLEN string variables

- .github/workflows/dask-migration-testing.yml
- .github/workflows/linting.yml
- .github/workflows/run-test-suite.yml
- .github/workflows/test-source-dist.yml
- setup.py
The Actions CI workflows have recently been producing jobs that all fail early (or are cancelled early due to parallel such failures) on the same setup errors, as copied in summary below. This PR aims to test, and then merge, a fix for this, so we can move onto seeing a true pass or fail output.
Despite what the note on the penultimate quoted line says, I am fairly certain this *is* actually a pip-related issue stemming from older versions of `pip` being used because (I was unaware of this before, but after investigation here I now realise) we are pretty behind in terms of versions specified for the so-called 'reusable' workflows which we specify in order to do common Actions jobs tasks such as checking out a repository and setting up Python, etc. By updating to the latest versions of …
> LAMA to Dask: updates to fix CI workflow setup errors

- cf/read_write/netcdf/netcdfread.py
During `cf.read`, prevents cached data elements from being gleaned from size-0 arrays. Allows `read_writeTest.test_read_broken_bounds` to pass.
> dask: Fix for cached elements from size-0 arrays

- cf/data/array/gatheredarray.py
- cf/data/array/mixin/__init__.py
- cf/data/array/mixin/compressedarraymixin.py
- cf/data/array/mixin/raggedarraymixin.py
- cf/data/array/subsampledarray.py
- cf/data/creation.py
- cf/data/data.py
- cf/test/test_Data.py
- cf/test/test_dsg.py
- cf/test/test_gathering.py
- cf/test/test_groups.py
- cf/test/test_subsampling.py
The recent change to the default dask file lock (#518) causes problems with compressed data: It's currently set up so that the each dask chunk has to compute another dask array. It does this nested compute with the synchronous scheduler - which it seemed to like - but now that `lock=False` it doesn't like it at all. 
The solution (well, hack) I have come up with involves redefining the other dask array with `da.from_array(..., lock=True)` and then all is well.
This is not great, and all of these compressed `to_dask_array` methods should really, if possible, integrate the other dask array into a single dask graph. That's one for later (post 3.14.0).
> dask: Force from_array lock=False for nested arrays in compressed chunks

- cf/field.py
- docs/source/tutorial.rst
> Fixed issues with captions of certain tutorials

- cf/data/array/netcdfarray.py
- cf/data/creation.py
- cf/data/data.py
- cf/test/test_read_write.py
It turns out that removing the concurrency lock for opening netCDF files is not (yet) safe in the netCDF-C library, so we should put it back for now. I had thought that separate opens/closes would be OK, but not so. This may be fixed in future version of netCDF-C. See, e.g. https://github.com/Unidata/netcdf4-python/issues/844 and https://github.com/pydata/xarray/issues/4100.
_Edit:_ The `test_Field_collapse` are still segfaulting intermittently, but less frequently with this. I think it may be due to the fact that each `from_array` call is creating its own lock, so its still possible for concurrent accesses that originate from the same file, e.g. `f + f.copy()`. The answer could be to create a common lock object and coordinate all access to a particular file around that. 
_Edit:_ …
> dask: Reinstate netCDF lock

- cf/data/data.py
Removes methods `Data.force_compute` and `Data.can_compute`, which were envisaged right at the start but are now needed.
> dask: Remove `Data.force_compute` and `Data.can_compute`

- cf/data/data.py
- cf/data/utils.py
Removes functions `is_small` and `is_very_small` from `data/utils.py`, which were envisaged right at the start , but never implemented, and we now know are not  needed
> dask: Remove `is_small` and `is_very_small`

- cf/functions.py
Upgrade `cf.environment` to be ready and correct for `3.14.0`, by:
* adding the two new dependency libraries (i.e. relative additions to `requirements.txt`) to the output, which notably includes `dask`, the package information on which might prove very useful with inevitable bug reports that will come in for the `.0` release!
* reordering a few libraries in the output listing, such that any C/Fortran underlying libraries are given first, then the NCAS CF Tools libraries at the very end (see comments on the corresponding dictionary summarising this).
> LAMA to Dask: update `cf.environment` with new dependencies

- cf/data/utils.py
- cf/test/test_Data_utils.py
Bug fix to get these lines from the `tutorial.rst` working:
```python
>>> d = cf.Data(['2004-02-29', '2004-02-30', '2004-03-01'], calendar='360_day')
>>> d.Units
<Units: days since 2004-02-29 360_day>
>>> print(d.array)
[0. 1. 2.]
>>> print(d.datetime_array)
[cftime.Datetime360Day(2004-02-29 00:00:00)
cftime.Datetime360Day(2004-02-30 00:00:00)
cftime.Datetime360Day(2004-03-01 00:00:00)]
```
> dask: Bug fix to `convert_to_reftime`

- docs/source/tutorial.rst
Fix the `GatheredArray` syntax in `tutorial.rst` - specifically using the new `compressed_dimensions` keyword.
> dask: Fix `GatheredArray` syntax in tutorial

- cf/data/array/netcdfarray.py
- cf/data/data.py
- cf/test/test_Data.py
- cf/test/test_Field.py
Gets this line to work in `tutorial.rst`: 
```python
>>> t[t.indices(latitude=cf.wi(51, 53))] = -99
```
> dask: `Data.__setitem__` ancillary masks

- docs/source/class/cf.AuxiliaryCoordinate.rst
- docs/source/class/cf.Bounds.rst
- docs/source/class/cf.CellMeasure.rst
- docs/source/class/cf.Count.rst
- docs/source/class/cf.Data.rst
- docs/source/class/cf.DimensionCoordinate.rst
- docs/source/class/cf.DomainAncillary.rst
- docs/source/class/cf.FieldAncillary.rst
- docs/source/class/cf.Index.rst
- docs/source/class/cf.List.rst
Nuked old `__query_*__` conditions (`__query_set__`, `__query_wi__`, `__query_wo__`) in accordance with the new version.
> Nuked __query_*__ conditions

- cf/data/data.py
- cf/test/test_Data.py
(Re-) Fixes #378. See that issue for details.
> dask: `Data.__init__` with no arguments

- cf/test/individual_tests
- cf/test/setup_create_field.py
Allows `setup_create_field.py` to pass. Change can be reverted when https://github.com/dask/dask/pull/9627 is accepted.
> dask: work-around for __setitem__ of masked element on str array 

- cf/data/mixin/deprecations.py
Deal with TODODASKMSG placeholders.
> dask: Deal with TODODASKMSG placeholders

- cf/data/data.py
- cf/test/test_Data.py
Fixes #434 
Allows `test_data_months_years` to pass.
> dask: `Data.datetime_array` bug fix

- cf/read_write/um/umread.py
Fixes #571
Adds the coordinate keys to the coordinate reference, and allows for missing units in the stash2standardname table.
> PP/UM files: Fix incomplete rotated pole coordinate reference constructs & coping with missing units

- cf/aggregate.py
- cf/data/data.py
- cf/test/test_aggregate.py
Towards #182, confirms that `cf.aggregate` works under the new "Dask way" with no modifications, with `test_basic_aggregate` failing instead due to specific issues elsewhere, namely:
* an issue with data comparison by `Data.equals`;
* an issue with construct comparison leading to field copies not being recognised as equal.
(Note to tidy up previous investigation/debugging branches, I created a fresh branch and re-applied commits to break down the fixes to specific parts.)
> LAMA to Dask: misc. fixes for a passing `test_aggregate`

- cf/data/array/abstract/array.py
- cf/data/array/cfanetcdfarray.py
- cf/data/array/gatheredarray.py
- cf/data/array/netcdfarray.py
- cf/data/array/raggedcontiguousarray.py
- cf/data/array/raggedindexedarray.py
- cf/data/array/raggedindexedcontiguousarray.py
- cf/data/array/subsampledarray.py
* Add missing `Container` mixin class inheritance to array classes. This is needed to pick up the cf docstring substitutions.
* Allow no-arg init of `CFANetCDFArray`
Necessary (but not sufficient) to get `test_docstring.py` to pass.
> dask: `Container` inheritance

- cf/data/array/cfanetcdfarray.py
- cf/data/array/fullarray.py
- cf/data/array/umarray.py
- cf/data/data.py
- cf/data/fragment/missingfragmentarray.py
- cf/data/fragment/netcdffragmentarray.py
- cf/data/fragment/umfragmentarray.py
- cf/field.py
Update docstring substitutions to mirror changes in `cfdm` 1.10.0.2.
> dask: Update docstring substitutions

- cf/data/dask_utils.py
- cf/data/data.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_Data.py
- docs/source/class/cf.Data.rst
Moves functionality from `PropertiesData.convert_reference_time` to `cf.data.dask_utils.cf_rt2dt` via `Data.convert_reference_time`.
> dask: `convert_reference_time` methods

- cf/data/data.py
- cf/test/test_Data.py
- cf/test/test_Field.py
Prevent this:
```python
>>>  import cf
>>> d = cf.Data([1, 2, 3])
>>>  e = d + ('sdf',)
NotImplemented has been set in the place of a dask array.
This could occur if any sort of exception is raised by a function that is run on chunks (via, for instance, da.map_blocks or
dask.array.core.elemwise). Such a function could get run at definition time in order to ascertain suitability (such as
data type casting, broadcasting, etc.). Note that the exception may be difficult to diagnose, as dask will have silently
trapped it and returned NotImplemented (for instance, see dask.array.core.elemwise). Print statements in a local copy
of dask are possibly the way to go if the cause of the error is not obvious.
>>>
```
replacing it with raising a `TypeError`, which is what numpy and Dask do.
> dask: Catch `NotImplemented` resulting from arithmetic

- .flake8
- .github/workflows/run-test-suite.yml
- .github/workflows/test-source-dist.yml
- .pre-commit-config.yaml
- cf/aggregate.py
- cf/decorators.py
- cf/field.py
- cf/read_write/um/umread.py
- cf/test/test_Data.py
- cf/test/test_Field.py
- cf/test/test_Query.py
- cf/test/test_regrid.py
- cf/umread_lib/extraData.py
- cf/umread_lib/umfile.py
- docs/source/conf.py
- scripts/cfa
Mostly (in terms of motivation) to fix a broken reference to the `flake8` repository, which moved from GitLab to GitHub at some point recently, which was causing the pre-commit workflow to halt awaiting GitLab authentication. This meant linting was erroring out. Now it should work, both in the sense of not erroring and of passing (locally I have fixed some outstanding `black` formatting violations). Mostly (in terms of code line changes) the `black` auto-fixes.
Trivial setup changes therefore no peer review required.
> Minor updates to config. files (fixes pre-commit workflow)

- cf/data/data.py
- cf/read_write/netcdf/netcdfread.py
- cf/test/test_Data.py
There was nothing particularly wrong with the original code, but the upcoming PR on CFA needs more performant and flexible approach.
> Refactor the storage and access of cached elements

- .github/workflows/run-test-suite.yml
- .github/workflows/test-source-dist.yml
Resolve #611 by finishing the closing up of that (@davidhassell has mostly done this via pre-release updates, thanks).
> Drop Python 3.7 support (via `numpy>=1.22` req.) loose ends

- cf/field.py
- cf/test/test_Field.py
Tightens up `Field.set_data` checking, preventing some cases that could cause inconsistencies downstream failures - better to trap the failures in set_data.
> Fix `Field.set_data` checking

- Changelog.rst
- cf/data/dask_regrid.py
- cf/data/data.py
- cf/read_write/um/umread.py
- cf/regrid/regrid.py
- cf/regrid/regridoperator.py
- cf/test/test_RegridOperator.py
Fixes #623 
* The previous approach loaded both the source and destination grid masks onto the weights, which had to be a dense `numpy` array since `scipy` sparse arrays do not support masks.
* The new approach keeps the weights in a  `scipy` sparse array, but creates a separate boolean mask to applied to the regridded data. 
* The change to `cf/regrid/regrid.py` pre-creates the sparse matrix representation in a returned regrid operator. This makes sense because the purpose of returning the operator is for efficiency in repeated future uses, so it makes sense not to have to do this every time.
* The change from `coo_array` to `csr_array` is because the latter is much more efficient at row slicing.
> Fix excessive regrid memory use

- Changelog.rst
- cf/read_write/um/umread.py
- docs/source/installation.rst
- docs/source/tutorial.py
- docs/source/tutorial.rst
Fixes #641 
Also some minor fixes for new syntax in the `tutorial.rst`; and increase the `scipy` minimum version (so that `from scipy.signal import window` is sure to work).
> Fix bug when reading single level (e.g. surface) UM files

- Changelog.rst
- cf/read_write/um/umread.py
Fixes #667
Prevents `_reorder_z_axis` from being called when there is only one Z level (and so there is nothing to reorder!).
> Fix bug in `cf.read` for some PP data with a single vertical level

- docs/source/field_analysis.rst
- docs/source/installation.rst
- docs/source/introduction.rst
- docs/source/performance.rst
- docs/source/tutorial.rst
Remove or replace the use of the words across the documentation that are considered bad practice (see, for example, [the Google dev docs style guide list of words to not use or to avoid](https://developers.google.com/style/word-list)) given the implication that something is easy when a user might not find it so, and that they are also effectively filler words so unnecessary, namely (see the case-by-case commits which tackle all cases of use of each related term):
* "simple" and "simply";
* "easy" and "easily";
* "just" (converting to "only" in the case that this is what is meant, being unambiguous).
This PR also fixes some sentences with minor typos that I have noticed in the process (see final commit).
> Docs: remove or replace cases of some subjective filler terms

- docs/source/conf.py
- release_docs
Added a new `dev-recipes` criterion to avoid regeneration of recipes when one simply has to test new documentation.
> Update release_docs and conf.py to avoid regeneration of documents

- cf/dimensioncoordinate.py
- cf/docstring/docstring.py
- cf/domain.py
- cf/test/test_DimensionCoordinate.py
- cf/test/test_Domain.py
The previous iteration of `cf.Domain.create_regular` and `cf.DimensionCoordinate.create_regular` checked explicitly for the range of the dimension to be divisible by the cellsize which is removed here and a note about the same is added in the docstring.
> Update create_regular methods to remove cellsize divisibility check

- Changelog.rst
- cf/field.py
- cf/mixin/fielddomain.py
- cf/test/test_Field.py
> Fix bug in `cf.Field.match_by_construct`

- Changelog.rst
- cf/aggregate.py
- cf/dimensioncoordinate.py
- cf/test/test_DimensionCoordinate.py
- cf/test/test_aggregate.py
- docs/source/class/cf.DimensionCoordinate.rst
> Record dimension coordinate cell characteristics

- Changelog.rst
- cf/read_write/read.py
- cf/test/test_read_write.py
> Fix bug that prevented `https://` netCDF files from being read

- Changelog.rst
- cf/field.py
- cf/test/test_Field.py
- cf/test/test_collapse.py
Fixes #701 
The crux of the issue was that `"sum"`, `"sum_of_weights"` and `"sum_of_weights2"` were missing from the `cf.field._collapse_weighted_methods` set.
> `cf.Field.collapse`: Fix "sum", "sum_of_weights" and "sum_of_weights2" when weighted

- .github/workflows/run-test-suite.yml
- .github/workflows/test-source-dist.yml
- cf/__init__.py
- cf/read_write/read.py
- cf/test/test_Field.py
- cf/test/test_Maths.py
Minor admin tweaks to:
* add some missing newer Python versions into the CI test workflow, including support for the new latest major version 3.12, which was released about 3 weeks ago which I tested locally to be compatible dependency-wise with cf and that all tests pass as they should with it (:heavy_check_mark:);
* add some test method skips where SciPy is required under-the-hood but not directly in the test, which produces a somewhat confusing error message as an outcome of `NameError: name 'convolve1d' is not defined. Did you mean: 'cf_convolve1d'?` because it can't find the `scipy` `convolve1d` and suggests our own wrapper;
* make two small formatting tweaks so that `test_style` i.e. `pycodestyle` passes.
> Testing and CI tidying including adding Python 3.12 job

- Changelog.rst
- cf/field.py
- cf/test/test_Field.py
- docs/source/class/cf.Data.rst
- docs/source/class/cf.Field.rst
Fixes #707
Also improves method order in API docs.
> Fix bug that caused `cf.Field.del_file_location` to fail when updating its metdata constructs

- Changelog.rst
- cf/data/creation.py
- cf/data/data.py
Fixes #706 
Uses the same technique as Dask.
> Allow data instantiation from a `xarray.DataArray` object 

- Changelog.rst
- cf/field.py
- cf/mixin/propertiesdata.py
- cf/test/test_Field.py
- cf/test/test_weights.py
- cf/weights.py
> Allow cell area calculation to ignore cell measure constructs

- Changelog.rst
- cf/field.py
- cf/test/test_Field.py
> Fix bug in `cf.Field.subspace` and `cf.Field.__getitem__` for some cyclic subspaces

- Changelog.rst
- cf/field.py
- cf/test/test_Field.py
Fixes #719 
Needs https://github.com/NCAS-CMS/cfdm/pull/288
> New `constructs` keyword to `cf.Field.insert_dimension`

- Changelog.rst
- cf/weights.py
Fixes #721 
No unit test - due to the lightly random nature, it's a bit tricky to write one. But the fix is pretty simple and it works for the use case described in the issue :)
> Fix bug when calculating UGRID cell areas when non-spatial coordinates span the discrete axis

- Changelog.rst
- cf/aggregate.py
- cf/regrid/regrid.py
- cf/test/test_aggregate.py
Fixes #723
Needs https://github.com/NCAS-CMS/cfdm/pull/290 for the new test to work.
> Allow DSG tractories with identical `trajectory_id` values to be   aggregated

- Changelog.rst
- cf/read_write/um/umread.py
> Recognise LBPROC 131072 when reading UM files

- Changelog.rst
- cf/field.py
> Improve `cf.Field.collapse` performance by lazily computing reduced axis coordinates

- Changelog.rst
- cf/field.py
- cf/mixin/fielddomain.py
- cf/test/test_Field.py
> Improve `cf.Field.__getitem__` performance by not re-calculating axis cyclicity

- cf/field.py
- cf/regrid/regrid.py
- cf/test/test_regrid.py
Bug fix for #715
Discovered when this tutorial example code failed with `ValueError: Z coordinate 'dimensioncoordinate0' must match exactly an element of 'axes' (['domainaxis0'])`
```python
>>> v = cf.read('vertical.nc')[0]
>>> print(v)
Field: eastward_wind (ncvar%ua)
-------------------------------
Data            : eastward_wind(time(3), air_pressure(5), grid_latitude(11), grid_longitude(10)) m s-1
Cell methods    : time(3): mean
Dimension coords: time(3) = [1979-05-01 12:00:00, 1979-05-02 12:00:00, 1979-05-03 12:00:00] gregorian
: air_pressure(5) = [850.0, ..., 50.0] hPa
: grid_latitude(11) = [23.32, ..., 18.92] degrees
: grid_longitude(10) = [-20.54, ..., -16.58] degrees
Auxiliary coords: latitude(grid_latitude(11), grid_longitude(10)) = [[67.12, ..., 66.07]] degrees_north
: …
```
> 1-d Z Cartesian regridding fix and test

- Changelog.rst
- cf/aggregate.py
> Fix bug in `cf.aggregate` that sometimes put a null transpose operation into the Dask grpah when one was not needed

- Changelog.rst
- cf/mixin/fielddomain.py
- cf/test/test_Domain.py
- cf/test/test_Field.py
Fix #758 and #756 (the former being the underlying issue and the latter a specific bug as a downstream effect) by overriding the `del_construct` inherited from cfdm to account for and update the store of `cyclic` axes. Previously we used the inherited method as-is so cyclic axes weren't updated and could get out of sync, notably contain axes which no longer existed due to deletion.
Note:
* The test `test_Domain_del_construct` added here will currently fail halfway-through due to #762, as noted in the test. I am fixing that next.
* I will add a note of two to the code in anticipation of some comments in review, for discussion.
> Override `del_construct` to update cyclic axes set when due

- Changelog.rst
- cf/query.py
- cf/test/test_Query.py
Close  #740, where we have come to realise that it might not be a good idea to support the feature for `wo` queries since there is the potential for a lot of confusion, namely I started to document and implement the following behaviour:
> open_lower: `bool`, optional
>              If True, open the interval at the lower
>              bound so that value0 is excluded from the
>              range and therefore included in the set of
>              values outside of the range captured by "wo".
>              By default the interval is closed so that
>              value0 is included in the range and not
>              captured by "wo".
and @davidhassell and I decided it might be too confusing when applied to "outside a range" as opposed to "inside a range", where it is quite intuitive. So …
> Open and half-open intervals for `wi` queries

- Changelog.rst
- cf/field.py
- cf/mixin/fielddomain.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_Domain.py
- cf/test/test_Field.py
Fix #762. The reason for the underlying issue was that the `Field.domain` attribute called `get_domain` which was inherited from `cfdm`, which doesn't have the concept of cyclic axes. So quite similar in terms of cause to #763 (maybe we should check there aren't further cases of cyclic axes not being accounted for, in case other bugs might exist?).
> Override `cfdm.Field.get_domain` to store axes cyclicity

- Changelog.rst
- cf/examplefield.py
- cf/test/test_functions.py
> Return a `FieldList` with `example_fields()`

- Changelog.rst
- cf/functions.py
- cf/test/test_functions.py
- docs/source/contributing.rst
To fix #774 
- Modified normalize_slice in cf/functions.py
- Added test to check confirm behaviour in cf/test/test_functions.functionTest.test_normalize_slice
- Added changes to changelog.
> Fix bug in certain cyclic subsets

- cf/aggregate.py
A bit tricky to test, as I can't see a case where the bug isn't benign: If two fields have different coordinate references, then they won't  get aggregated anyway, regardless of whether or not any coordinate references are attached to dimension coordinates (which is the "bug")
> Correct finding coordrefs in `cf.aggregate`

- .pre-commit-config.yaml
- cf/field.py
- cf/test/test_Data.py
- cf/test/test_functions.py
- cf/weights.py
Update linting package versions for Python 3.12
> Update linting package versions for Python 3.12

- Changelog.rst
- cf/cellmethod.py
- cf/field.py
- cf/mixin/fielddomain.py
- cf/test/test_Field.py
- cf/test/test_functions.py
- docs/source/class/cf.Domain.rst
- docs/source/class/cf.Field.rst
Fixes #784
- The changes to `test_functions.py` are left-over linting from a previous PR.
- The changes to `cf.FIeld._binary_operation` look scarier than they are :). We've essentailly just moved from 2 cases (axis defined by dim coord, or axis defined by aux coord) to 3 cases (axis defined by dim coord, or axis defined by aux coord, or discrete axis), and the rest is largely just a bit code reorganisation around that (this is old and horrible code!)
- This doesn't do what we might hope for in the DSG discrete axis case, but that's not a fault of this code. In this case, it's doing the right thing with the discrete axes, but is the _non_-discrete axes that unexpected  broadcasting, because these axes have no identifying coordinates - that a sperate issue to be dealt with elsewhere.
> Field combination

- docs/source/tutorial.rst
'FieldList' object has no attribute 'properties' so I changed t = cf.read('file.nc') to t = cf.read('file.nc')[1]
> fixing a mistake in tutorial.rst

- Changelog.rst
- cf/field.py
- cf/maths.py
- cf/test/test_Field.py
- cf/test/test_Maths.py
> Fix incorrect result units for some differential operators

- Changelog.rst
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_AuxiliaryCoordinate.py
- cf/test/test_Field.py
- docs/source/class/cf.AuxiliaryCoordinate.rst
- docs/source/class/cf.Bounds.rst
- docs/source/class/cf.CellMeasure.rst
- docs/source/class/cf.Count.rst
- docs/source/class/cf.DimensionCoordinate.rst
- docs/source/class/cf.DomainAncillary.rst
- docs/source/class/cf.Field.rst
- docs/source/class/cf.FieldAncillary.rst
- docs/source/class/cf.Index.rst
- docs/source/class/cf.List.rst
> New method: `cf.Field.filled`

- cf/query.py
No issue since discussed offline.
> Minor updates for `open_lower` and `open_upper` `cf.wi` query arguments

- docs/cheat_sheet.html
Quick PR to fix a link to the PDF cheat sheet which is broken since the hash in the link wasn't removed somehow in the build process: see https://ncas-cms.github.io/cf-python/cheat_sheet.html and try to click 'pdf' (or open it in a new tab, remove the hash component and it works). I want to update this manually in the built HTML since I want to update the Intro. Scientific Computing to include a link to the cheat sheet from the current docs and don't want a broken link sitting there for someone to find.
I would have just pushed this fix as a lone commit if it weren't for the fact that I wanted to check if we need to update the release script in case anything is wrong that led to the hash component not getting removed to break the link, but actually taking a quick look the logic looks fine …
> Fix to broken link to PDF cheatsheet

- docs/source/recipes/plot_16_recipe.py
- docs/source/recipes/recipe_list.txt
This is the first of three recipes created this summer by our first summer student of two, Natalia. It has been prepared in the form consistent with the existing recipes.
I have only added the Python script - @bewithankit, I see four different files per recipe, is this one sufficient or do I need to generate the other three (`plot_N_recipe_codeobj.pickle`, `plot_N_recipe.ipynb` and `plot_N_recipe.rst`) from this for this PR, or can this be done at release time (or is the creation automatic from release r other procedures)? I will be adding the other five student-made recipes in the next few (working) days - all are in the same format as the canonical Python script.
Given the nature of recipes, the script itself should be self-contained and self-explanatory. But for context, I will add …
> Add new recipe (16) by summer student: projection subplots

- Changelog.rst
- cf/cfimplementation.py
- cf/data/data.py
- cf/dimensioncoordinate.py
- cf/mixin/fielddomain.py
- cf/regrid/regrid.py
- cf/test/test_DimensionCoordinate.py
- cf/test/test_Field.py
Fixes #828.
This PR fixes and simplifies the treatment of cyclic subspaces in `cf.mixin.fielddomain._indices`. In the process, it refactors `cf.mixin.fielddomain.anchor` by moving the business-end of that to the new `cf.DimensionCoordinate.anchor`. This new method also allows for "cell" anchoring, which we might like to use later (see #824).
> Fix bug where `cf.Field.subspace` doesn't always correctly handle   global cyclic subspaces

- Changelog.rst
- cf/cfimplementation.py
- cf/data/dask_regrid.py
- cf/data/data.py
- cf/docstring/docstring.py
- cf/regrid/regrid.py
- cf/test/test_regrid_featureType.py
> Allow 'nearest_dtos' 2-d regridding to work with discrete sampling geometry source grids

- Changelog.rst
- cf/field.py
- cf/test/test_formula_terms.py
Close #802, via approach summarised in https://github.com/NCAS-CMS/cf-python/issues/802#issuecomment-2626656549. Tests, docs and changelog updated appropriately.
> Add new `key` parameter to `compute_vertical_coordinates`

- Changelog.rst
- cf/dimensioncoordinate.py
- cf/test/test_DimensionCoordinate.py
- docs/source/recipes/plot_13_recipe.py
>  Fix bug that caused wrong directions from `cf.DimensionCoordinate.direction`

- docs/source/recipes/plot_04_recipe.py
- docs/source/recipes/plot_16_recipe.py
- docs/source/recipes/plot_17_recipe.py
- docs/source/recipes/plot_18_recipe.py
- docs/source/recipes/plot_19_recipe.py
- docs/source/recipes/plot_20_recipe.py
- release_docs
Was intending to push these directly as commits, but since we've had some last-minute bug fixes I will use a PR to keep it self-contained. This PR is mostly tweaks to the numbered blocks in the new recipes, to get all `gopen()` and `gclose()` wrapped code into one block, else plots don't seem to emerge through the Sphinx Gallery build (in future I'll look into ways to fix this so we can keep the blocks separated out, which is clearer, but for the new release there is no time to investigate). Otherwise there is one update to a deprecated keyword and a new option for the `release_docs` script to facilitate recipe build debugging.
No review required as infrastructural and non-controversial and I am due to do the release ASAP.
> Recipes tweaks for Sphinx Gallery build and rendering

- cf/test/test_DimensionCoordinate.py
- docs/source/conf.py
- docs/source/recipes/plot_08_recipe.py
- docs/source/recipes/plot_12_recipe.py
- docs/source/recipes/plot_13_recipe.py
- docs/source/recipes/plot_17_recipe.py
- docs/source/recipes/plot_18_recipe.py
- docs/source/recipes/plot_19_recipe.py
`pre-commit` wants to reorder the imports in some of the recipe files, but due to the esmpy/shapely class we don't want this to happen - so we can add some "isort:skip_file" directives to the relevant Python recipe files.
See https://pycqa.github.io/isort/ for details.
> Add "isort:skip_file" directives to recipes

- Changelog.rst
> Allow the HDF5 "chunk cache" to be set from `cf.write`

- Changelog.rst
- cf/data/data.py
- cf/mixin/propertiesdata.py
- cf/mixin/propertiesdatabounds.py
- cf/test/test_Data.py
- cf/test/test_DimensionCoordinate.py
- cf/test/test_Field.py
- docs/source/class/cf.AuxiliaryCoordinate.rst
- docs/source/class/cf.Bounds.rst
- docs/source/class/cf.CellConnectivity.rst
- docs/source/class/cf.CellMeasure.rst
- docs/source/class/cf.Count.rst
- docs/source/class/cf.Data.rst
- docs/source/class/cf.DimensionCoordinate.rst
- docs/source/class/cf.DomainAncillary.rst
- docs/source/class/cf.DomainTopology.rst
- docs/source/class/cf.Field.rst
- docs/source/class/cf.FieldAncillary.rst
- docs/source/class/cf.Index.rst
- docs/source/class/cf.List.rst
> New `to_units` methods to allow changing units in a chain

- docs/source/contributing.rst
- docs/source/installation.rst
- Added a section in installation do s below conda installation instructions that talks about what to do when installing cf alongside Jupyter (common use case)
- Attempt to give guidance on how to solve NCAS-CMS/cf-python#883
> Added troubleshooting for installing cf next to Jupyter and conda
