NCAS-CMS/cf-python

cf/test/test_dsg.py

Not really harmful, but not necessary I think?

Remove unnecessary semicolon

---

cf/abstract/coordinate.py
cf/field.py
cf/umread_lib/umfile.py

I have spotted some instances of redundant logic or duplication which can be reduced, so here are some suggestions to simplify those cases.
I've checked that the test battery results are not affected by this change.

Code: consolidate some logic

---

Changelog.rst
cf/field.py
cf/mixin/propertiesdatabounds.py

added geometry command (+ some PEP8)

---

cf/field.py
cf/test/test_Field.py

has_construct bug fix + docs (Fixes #67)

---

CONTRIBUTING.md

Contributing (fixes #64)

---

cf/aggregate.py

property clarification

---

cf/mixin/propertiesdata.py
cf/mixin/propertiesdatabounds.py
cf/test/test_DimensionCoordinate.py

Extend unary operations to apply to bounds

---

Changelog.rst
cf/__init__.py
requirements.txt

Update to cfunits 3.3.1 (https://github.com/NCAS-CMS/cfunits/issues/19)

cfunits 3.3.1

---

cf/functions.py
cf/read_write/um/umread.py
cf/test/test_pp.py
docs/source/function.rst
scripts/cfa

new method stash2standard_name, cfa fixes

new method stash2standard_name, cfa fixes

---

cf/read_write/um/umread.py

removed needless reads from disk in logger commands

removed needless reads from disk in logger commands

---

cf/data/data.py

Minor fixes to `__getitem__` and `__setitem__`

Bug fixes to __getitem__ and __setitem__

---

Changelog.rst
cf/__init__.py
cf/data/data.py
cf/functions.py
docs/source/conf.py
docs/source/performance.rst

Remove the ability to parallelize the collapse operation with mpirun

---

Changelog.rst
cf/__init__.py
cf/cfdatetime.py
cf/data/data.py
cf/mixin/fielddomain.py
cf/query.py
docs/source/installation.rst
requirements.txt

Upgrade to cfunits 3.3.2

---

Changelog.rst
cf/field.py

Fix logging syntax

---

cf/field.py
cf/regrid/regridoperator.py
cf/regrid/utils.py

Fix treatment of missing ESMF library

---

cf/data/data.py

Fixes (for now) #252
Replace the messy #253

dask: Force `Data.can_compute` to return True (for now ...)

---

Changelog.rst
cf/__init__.py
cf/read_write/read.py
cf/test/test_pp.py
docs/source/installation.rst
requirements.txt
scripts/cfa

Fix for umversion in `cf.read`

---

cf/data/data.py
cf/test/test_Data.py

Just some tidying up and a few more tests.

dask: `Data.datum`

---

Changelog.rst
cf/__init__.py
cf/mixin/propertiesdatabounds.py
cf/test/test_DimensionCoordinate.py

Fix for setting bounds with different but equivalent units

---

cf/aggregate.py
cf/data/abstract/filearray.py
cf/data/creation.py
cf/data/functions.py
cf/data/mixin/deprecations.py
cf/data/netcdfarray.py
cf/data/umarray.py
cf/dimensioncoordinate.py
cf/mixin/fielddomain.py
cf/read_write/netcdf/netcdfread.py
cf/read_write/netcdf/netcdfwrite.py
cf/read_write/um/umread.py
cf/test/test_aggregate.py
cf/test/test_read_write.py

* This PR requires https://github.com/NCAS-CMS/cfdm/pull/196 to be merged into the (master of) `cfdm` being used.
* Only tests `setup_create_field.py` and `test_read_write.py` have been tested. The latter has some skips relating to `cf.aggregate`, which will be fixed elsewhere.
* Running these test on my local machine "hasn't seg faulted for a while". _edit - Oh, it just did 2 out of the last 3 times I ran test_read_write.py_

dask: Basic daskified reading and writing

---

docs/installation.html
docs/source/installation.rst

Update conda instructions

---

cf/data/data.py
cf/test/test_Data.py

Hopefully self explanatory :)
Needs https://github.com/NCAS-CMS/cfdm/pull/213

dask: Implement orthogonal setitem assignment when 2 or more indices are lists/1-d arrays

---

cf/__init__.py
cf/read_write/read.py
cf/read_write/um/umread.py

Test of 3.13.1

---

cf/data/data.py
cf/mixin/propertiesdata.py
cf/mixin/propertiesdatabounds.py
cf/test/test_AuxiliaryCoordinate.py
cf/test/test_Field.py
docs/source/class/cf.AuxiliaryCoordinate.rst
docs/source/class/cf.Bounds.rst
docs/source/class/cf.CellMeasure.rst
docs/source/class/cf.Count.rst
docs/source/class/cf.Data.rst
docs/source/class/cf.DimensionCoordinate.rst
docs/source/class/cf.DomainAncillary.rst
docs/source/class/cf.Field.rst
docs/source/class/cf.FieldAncillary.rst
docs/source/class/cf.Index.rst
docs/source/class/cf.List.rst

More or less a renaming of `mask_invalid` to `masked_invalid` (plus a bit of docs housekeeping).

dask: `Field masked_invalid`

---

Changelog.rst
cf/read_write/um/umread.py

Fixes #487
Also tidy up changelog

Fix for UM stash codes that are area means returning incorrect cell methods

---

cf/data/data.py
cf/field.py
cf/test/test_Data.py
cf/test/test_Field.py

Mainly setting the `_axes` attribute correctly in `Data.percentile`.

dask: `Field.percentile`

---

cf/data/data.py
cf/mixin/propertiesdata.py
cf/mixin/propertiesdatabounds.py
cf/test/test_Data.py
cf/test/test_DimensionCoordinate.py
cf/test/test_Field.py
docs/source/class/cf.AuxiliaryCoordinate.rst
docs/source/class/cf.Bounds.rst
docs/source/class/cf.CellMeasure.rst
docs/source/class/cf.Count.rst
docs/source/class/cf.Data.rst
docs/source/class/cf.DimensionCoordinate.rst
docs/source/class/cf.DomainAncillary.rst
docs/source/class/cf.Field.rst
docs/source/class/cf.FieldAncillary.rst
docs/source/class/cf.Index.rst
docs/source/class/cf.List.rst

Set on data `persists` methods on constructs.

dask: `Field.persist`

---

cf/field.py

Improve `Field.collapse` error messages

Improve `Field.collapse` error messages

---

Changelog.rst
cf/dimensioncoordinate.py
cf/test/test_DimensionCoordinate.py

Fix `DimensionCoordinate.create_bounds` for cyclic coordinates & improve docs

---

cf/auxiliarycoordinate.py

Fixed typo

---

cf/data/data.py
cf/test/test_Data.py

Allow weighted sums in `Data.stats`.

dask: Allow weighted sums in `Data.stats`

---

cf/mixin/fielddomain.py
cf/test/test_Field.py

dask: Indices equality test order

---

cf/data/data.py
cf/data/mixin/deprecations.py
cf/field.py
cf/regrid/regrid.py
cf/regrid/regridoperator.py

dask: Housekeeping

---

cf/maths.py
cf/test/test_Data_utils.py
cf/test/test_Field.py

dask: Miscellaneous test fixes

---

docs/recipes/README.html
docs/recipes/index.html
docs/recipes/plot_1_recipe.html
docs/recipes/plot_2_recipe.html
docs/recipes/plot_3_recipe.html
docs/recipes/plot_4_recipe.html
docs/recipes/plot_5_recipe.html
docs/recipes/sg_execution_times.html

Updated Sphinx-Gallery

---

Changelog.rst
cf/data/dask_utils.py
cf/test/test_Data.py

Remove UserWarning from `cf.Field.percentile`

---

cf/constructs.py
docs/source/class/cf.Field.rst

Tidy up the docs, following suggestions by @JonathanGregory.

Documentation tidy

---

Changelog.rst
cf/field.py
cf/test/test_formula_terms.py

Fix bounds properties on computed vertical coordinates

---

Changelog.rst
scripts/cfa

Fix bug when using the `-d` option to the `cfa` script 

---

docs/recipes/plot_3_recipe.html
docs/recipes/plot_6_recipe.html
docs/recipes/plot_8_recipe.html

Remove the output warning messages displayed in some Spinx Gallery pages.

Housekeeping

---

docs/source/_static/customise-alabaster.css
docs/source/conf.py

Scrollable Navigation Menu (Sidebar)

---

cf/data/data.py
cf/test/test_regrid.py
docs/source/conf.py
docs/source/recipes/plot_11_recipe.py

Regrid chunks

---

Changelog.rst
cf/field.py
cf/test/test_TimeDuration.py
cf/test/test_collapse.py
cf/timeduration.py

Fix failure when creating 'T: mean within days time: minimum over days'' collapse

---

Changelog.rst
cf/__init__.py
cf/functions.py
docs/source/installation.rst
requirements.txt

Pin to `dask>=2025.5.1`
